export const IDENTITY_ROUTES=Object.freeze({
  ZHANG:Object.freeze(['ZHANG_OPEN_4F','M2','M1','ZHANG_OUTBOUND_8F','M4','ZHANG_SECOND_CAMPUS_SECURITY','M5','M3','ZHANG_2F_PRESENCE_CHECK','ZHANG_4F_WITNESS_RETURN','ZHANG_3F_OBSERVATION_RECORD','M6','M7','B2','ZHANG_3F_ARCHIVE','M9']),
  LI:Object.freeze(['M1','M2','LI_DUTY_CALL_2000','LI_ER_2005','LI_RETURN_DUTY_2117','LI_2117_PATROL','LI_RETURN_DUTY_0033','LI_ER_0033','LI_316_ARCHIVE','LI_OUTBOUND_8F','M4','M5','M6','M7','B2','LI_3F_EVIDENCE','M9']),
  ZHOU:Object.freeze(['ZHOU_OPEN_8F','M4','M5','M1','ZHOU_1F_PHOTO','ZHOU_SECURITY_TALK','M3','M2','ZHOU_1F_WARNING_CALL','ZHOU_2F_WARNING_READBACK','ZHOU_2117_RETURN','M6','M7','B2','M8','M9']),
  CHEN:Object.freeze(['CHEN_OPEN_SKYBRIDGE','M4','M5','M1','M2','CHEN_1F_TRANSIT_LOG','M3','CHEN_2F_HANDOFF_RECEIPT','CHEN_4F_DESTINATION_CHECK','CHEN_3F_ROUTE_RECONCILE','M6','M7','B2','CHEN_M8_DISPATCH','M9'])
});

export const ROUTE_STEPS=Object.freeze({
  ZHANG_OPEN_4F:{zoneId:'first_campus_4f',spawn:'m3_4f_nursing_station',label:'護理站報到',time:'16:50'},
  ZHOU_OPEN_8F:{zoneId:'first_campus_8f',spawn:'m6_8f_bridge_entry',label:'院史長廊',time:'16:50'},
  CHEN_OPEN_SKYBRIDGE:{zoneId:'skybridge',spawn:'m7_skybridge_mid',label:'天橋來電',time:'16:50'},
  M1:{zoneId:'first_campus_3f',spawn:'m0_316_entrance',label:'316 交班',time:'17:00'},
  ZHANG_OUTBOUND_8F:{zoneId:'first_campus_8f',spawn:'first_8f_lift',label:'八樓天橋前往第二院區',time:null},
  M2:{zoneId:'first_campus_4f',spawn:'m3_4f_nursing_station',label:'病房查房',time:null},
  M3:{zoneId:'first_campus_2f',spawn:'m4_2f_er_arrival',label:'急診會診',time:null},
  LI_DUTY_CALL_2000:{zoneId:'first_campus_4f',spawn:'m2_4f_duty_room',label:'值班室休息',time:'20:00'},
  LI_ER_2005:{zoneId:'first_campus_2f',spawn:'m4_2f_er_bays',label:'急診新病人',time:'20:05'},
  LI_RETURN_DUTY_2117:{zoneId:'first_campus_4f',spawn:'m2_4f_duty_room',label:'回值班室',time:'21:15'},
  LI_2117_PATROL:{zoneId:'first_campus_3f',spawn:'m0_3f_corridor',label:'三樓查哨',time:'21:17'},
  LI_RETURN_DUTY_0033:{zoneId:'first_campus_4f',spawn:'m2_4f_duty_room',label:'00:33 急診來電',time:'00:30'},
  LI_ER_0033:{zoneId:'first_campus_2f',spawn:'m4_2f_er_triage',label:'00:33 異常掛號',time:'00:33'},
  LI_316_ARCHIVE:{zoneId:'first_campus_3f',spawn:'m0_316_office',label:'316 舊終端',time:null},
  LI_OUTBOUND_8F:{zoneId:'first_campus_8f',spawn:'m6_8f_bridge_entry',label:'前往第二院區',time:null},
  LI_3F_EVIDENCE:{zoneId:'first_campus_3f',spawn:'m0_3f_corridor',label:'三樓交叉核對',time:'03:30'},
  M4:{zoneId:'second_campus_5f',spawn:'second_5f_lift',label:'504B 會診',time:null},
  ZHANG_SECOND_CAMPUS_SECURITY:{zoneId:'second_campus_1f',spawn:'second_1f_lift',label:'警衛室的黑咖啡',time:null},
  M5:{zoneId:'skybridge',spawn:'bridge_from_second',label:'天橋回程',time:null},
  ZHANG_6F_FORESHADOW:{zoneId:'first_campus_8f',spawn:'first_8f_lift',label:'樓層顯示異常',time:null},
  ZHOU_1F_PHOTO:{zoneId:'first_campus_1f',spawn:'first_1f_guard_back',label:'舊照片',time:null},
  ZHOU_SECURITY_TALK:{zoneId:'first_campus_1f',spawn:'first_1f_guard_back',label:'警衛的回憶',time:null},
  ZHOU_1F_WARNING_CALL:{zoneId:'first_campus_1f',spawn:'first_1f_guard_back',label:'把警告說完整',time:null},
  ZHOU_2F_WARNING_READBACK:{zoneId:'first_campus_2f',spawn:'m4_2f_er_triage',label:'確認警告已被聽懂',time:null},
  ZHOU_2117_RETURN:{zoneId:'first_campus_3f',spawn:'m0_3f_corridor',label:'三樓查哨',time:'21:17'},
  M6:{zoneId:'phantom_6f',spawn:'phantom_6f_lift',label:'錯停的六樓',time:null},
  M7:{zoneId:'first_campus_1f',spawn:'first_1f_guard_back',label:'備援控制盤',time:'02:17'},
  B2:{zoneId:'b2_archive',spawn:'b2_archive_entry',label:'封存隔離層',time:null},
  M8:{zoneId:'first_campus_4f',spawn:'m3_4f_nursing_station',label:'身分拒絕',time:null},
  ZHANG_2F_PRESENCE_CHECK:{zoneId:'first_campus_2f',spawn:'m4_2f_er_triage',label:'急診在場紀錄複核',time:null},
  ZHANG_4F_WITNESS_RETURN:{zoneId:'first_campus_4f',spawn:'m3_4f_nursing_station',label:'回訪 408C',time:null},
  ZHANG_3F_OBSERVATION_RECORD:{zoneId:'first_campus_3f',spawn:'m0_316_office',label:'床邊觀察交班',time:null},
  ZHANG_3F_ARCHIVE:{zoneId:'first_campus_3f',spawn:'m0_3f_corridor',label:'三樓文史館',time:'03:30'},
  CHEN_1F_TRANSIT_LOG:{zoneId:'first_campus_1f',spawn:'first_1f_guard_back',label:'跨院出入核對',time:null},
  CHEN_2F_HANDOFF_RECEIPT:{zoneId:'first_campus_2f',spawn:'m4_2f_er_triage',label:'急診交接回執',time:null},
  CHEN_4F_DESTINATION_CHECK:{zoneId:'first_campus_4f',spawn:'m3_4f_nursing_station',label:'目的地現場複核',time:null},
  CHEN_3F_ROUTE_RECONCILE:{zoneId:'first_campus_3f',spawn:'m0_3f_corridor',label:'轉送鏈交叉核對',time:null},
  CHEN_M8_DISPATCH:{zoneId:'b1_dispatch_hub',spawn:'chen_b1_dispatch',label:'地下救護車接駁調度室',time:'03:30'},
  M9:{zoneId:'first_campus_3f',spawn:'m0_316_office',label:'最後交班',time:null}
});
Object.values(ROUTE_STEPS).forEach(Object.freeze);
