import assert from 'node:assert/strict';
import { IdentityManager } from './src/core/IdentityManager.js';
import { IdentityLoopPanel } from './src/ui/IdentityLoopPanel.js';
const manager=IdentityManager.createForTest('LI');
while(manager.currentRouteStep!=='M9')assert.equal(manager.completeRouteStep(manager.currentRouteStep),true);
assert.equal(manager.commitM9('LI','LI').type,'GOOD_END');assert.deepEqual(manager.commitM9('ZHANG','ZHANG'),{ok:false,reason:'ALREADY_COMMITTED'});
globalThis.document={getElementById:()=>null};
const panel=new IdentityLoopPanel(IdentityManager.createForTest('LI'));
while(panel.manager.currentRouteStep!=='M9')assert.equal(panel.manager.completeRouteStep(panel.manager.currentRouteStep),true);
const endings=[],callbacks=[];
panel.showEnding=result=>endings.push(result.type);
panel.onCommit=result=>callbacks.push(result.type);
assert.equal(panel.commit('LI','LI').type,'GOOD_END');
assert.equal(panel.commit('LI','LI').reason,'ALREADY_COMMITTED');
assert.deepEqual(endings,['GOOD_END']);
assert.deepEqual(callbacks,['GOOD_END']);
delete globalThis.document;
console.log('PASS M9 single irreversible commit');
