import assert from 'node:assert/strict';
import * as THREE from 'three';
import {WorldRouter} from './src/world/WorldRouter.js';
import {ANNIE_STATES, updateAnnieArt} from './src/art/AnnieArt.js';
import {gameState} from './src/core/GameState.js';

const context=new Proxy({measureText:t=>({width:t.length*20})},{get:(o,k)=>o[k]||(()=>({addColorStop(){}}))});
global.document={querySelector:()=>null,addEventListener(){},createElement:()=>({width:0,height:0,getContext:()=>context})};
const router=new WorldRouter(new THREE.Scene(),new THREE.PerspectiveCamera(),null);
function assertAnnie(group,state){
  assert(group,`${state} mannequin must exist`);
  assert.equal(group.userData.characterId,'ANNIE_CPR_TRAINING_MANNEQUIN');
  assert.equal(group.userData.state,state);
  assert(group.getObjectByName('Annie_Head'),'shared mannequin head missing');
  assert(group.getObjectByName('Annie_Torso'),'shared mannequin torso missing');
  assert(!group.getObjectByName('Annie_Stethoscope'),'stethoscope must remain off Annie');
  assert(!group.getObjectByName('Annie_MouthAirway'),'trainer must not gain an airway mechanism');
  assert(group.getObjectByName('Annie_MoldedNose'),'anatomical nose inspection anchor missing');
  assert(group.getObjectByName('Annie_SmoothVinylFace'),'face must read as molded vinyl');
  assert(group.getObjectByName('Annie_WhiteCoat'),'yellowed white coat missing');
  assert(group.getObjectByName('Annie_Scrubs'),'gray-green scrub layer missing');
  assert.equal(group.userData.assetVersion,'ANNIE_CHARACTER_V1');
  const shoe=group.getObjectByName('AnnieCharacter_Annie_Mat_Shoe');assert(shoe?.isMesh,'merged work shoes missing');
  assert(group.getObjectByName('AnnieCharacter_Annie_Mat_Eye'),'fixed painted eyes missing');
  assert(group.getObjectByName('AnnieCharacter_Annie_Mat_Mouth'),'painted closed lips missing');
  assert(group.getObjectByName('Annie_Local_CoolWhite_Practical')?.castShadow,'existing practical must remain');
  assert(!Object.hasOwn(group.userData,'inscription'),'the mannequin does not own the stethoscope clue');
  assert.equal(group.userData.modelHeight,1.65,'standing reference height remains 165 cm');
  let meshCount=0;
  group.traverse(object=>{
    if(!object.isMesh)return;
    meshCount++;
    assert.notEqual(object.geometry.type,'BoxGeometry',`${object.name} must use rounded mannequin geometry`);
  });
  assert(meshCount>=18&&meshCount<=24,'merged anatomy and clothing must remain within the mobile character draw budget');
  let triangles=0;group.traverse(o=>{if(o.isMesh){triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;for(const v of o.geometry.attributes.position.array)assert(Number.isFinite(v));}});assert(triangles<=28000,'character triangle budget exceeded');
}

const threeF=router.loadZone('first_campus_3f');
const storage=threeF.levelInstance.anneGroup;
assertAnnie(storage,ANNIE_STATES.STORAGE_STATIC);
assert(storage.getObjectByName('Annie_Stool'),'M1 Annie must sit on the storage stool');
storage.updateMatrixWorld(true);
const cartBounds=new THREE.Box3().setFromObject(storage);
assert(cartBounds.min.y>=.82,'supine trainer must not penetrate cart');
assert(cartBounds.min.y<.87,'supine trainer must rest on cart, not float');
assert(cartBounds.min.x>=12.62&&cartBounds.max.x<=14.35,'trainer must fit the existing teaching bed');
assert(new THREE.Vector3(0,0,1).applyQuaternion(storage.getWorldQuaternion(new THREE.Quaternion())).y>.99,'teaching trainer must lie face-up');
assert.equal(threeF.levelInstance.anneStethoscopeProp,undefined,'the stethoscope clue belongs to the 6F investigation');
const storageElapsed=storage.userData.rig.elapsed;
updateAnnieArt(storage,1);
assert.equal(storage.userData.rig.elapsed,storageElapsed,'M1 storage mannequin remains completely static');
const bridge=router.loadZone('skybridge').bridgeDoppelganger;
assertAnnie(bridge,ANNIE_STATES.BRIDGE_MANIFEST);
updateAnnieArt(bridge,.5);
assert.equal(bridge.userData.pose,ANNIE_STATES.BRIDGE_MANIFEST);
assert.notEqual(bridge.userData.rig.head.rotation.z,0,'bridge idle keeps a tiny mechanical settling motion');
assert(bridge.getObjectByName('Annie_OverlappedHands'),'bridge pose must hold both hands together');
bridge.updateMatrixWorld(true);
assert(bridge.getObjectByName('Annie_HandStack_Top').getWorldPosition(new THREE.Vector3()).y>1.05,'bridge hands remain lifted and extended');
const bottomHand=bridge.getObjectByName('Annie_HandStack_Bottom').getWorldPosition(new THREE.Vector3());
const topHand=bridge.getObjectByName('Annie_HandStack_Top').getWorldPosition(new THREE.Vector3());
assert(bottomHand.distanceTo(topHand)<.065,'bridge hands must remain overlapped');

gameState.setFlag('FLOOR6_STETHOSCOPE_FOUND',false);
gameState.setFlag('FLOOR6_STETHOSCOPE_INSPECTED',false);
const phantom6F=router.loadZone('phantom_6f');
assert(phantom6F.zoneGroup.getObjectByName('Phantom6F_ElevatorDoors'),'6F elevator landing must retain visible elevator doors');
const stethoscope=phantom6F.stethoscopeProp;
assert.equal(stethoscope.visible,false,'the 6F stethoscope stays buried until searched');
assert.equal(phantom6F.stethoscopeSearch.userData.interactable,true);
assert.equal(phantom6F.stethoscopeInspect.userData.interactable,false);
assert(stethoscope.getObjectByName('Floor6_Stethoscope_Engraving'),'the close inspection prop needs a visible engraved plate');
assert.equal(stethoscope.userData.inscription,'祝 守恆 醫師 1997 執業誌慶');
gameState.setFlag('FLOOR6_STETHOSCOPE_FOUND',true);
phantom6F.syncStoryState();
assert.equal(stethoscope.visible,true,'searching reveals the stethoscope');
assert.equal(phantom6F.stethoscopeSearch.userData.interactable,false);
assert.equal(phantom6F.stethoscopeSearch.visible,false,'inactive search hitbox must stop blocking the inspection ray');
assert.equal(phantom6F.stethoscopeSearch.layers.mask,0,'inactive search hitbox must leave the raycast layer');
assert.equal(phantom6F.stethoscopeInspect.userData.interactable,true);
assert.equal(phantom6F.stethoscopeInspect.visible,true,'inspection hitbox must accept the next raycast');
assert.notEqual(phantom6F.stethoscopeInspect.layers.mask,0,'inspection hitbox must be on the raycast layer');
gameState.setFlag('FLOOR6_STETHOSCOPE_INSPECTED',true);
phantom6F.syncStoryState();
assert.equal(phantom6F.stethoscopeInspect.userData.interactable,false,'inspection cannot be repeated after reading the engraving');
assert.equal(phantom6F.stethoscopeInspect.visible,false,'completed inspection hitbox must stop receiving rays');

const cpr=phantom6F.zoneGroup.getObjectByName('Annie_FLOOR6_CPR');
assertAnnie(cpr,ANNIE_STATES.FLOOR6_CPR);
updateAnnieArt(cpr,0);
assert(cpr.getObjectByName('Annie_OverlappedHands'),'CPR uses overlapped hands');
assert(cpr.getObjectByName('Annie_Local_CoolWhite_Practical')?.castShadow,'Annie needs local cool-white shadowed light');
cpr.updateMatrixWorld(true);
const cprHands=cpr.getObjectByName('Annie_HandStack_Top').getWorldPosition(new THREE.Vector3());
const patient=phantom6F.zoneGroup.getObjectByName('Annie_Patient_CPR_Target');
patient.updateWorldMatrix(true,false);
const patientCenter=patient.getWorldPosition(new THREE.Vector3());
assert(cprHands.distanceTo(patientCenter)<0.35,'overlapped CPR hands must reach the burned patient contact point');
const patientTop=patientCenter.y+patient.geometry.parameters.radius*patient.scale.y;
assert(Math.abs(cprHands.x-patientCenter.x)<0.1,'CPR hands must be centered over the patient chest');
assert(Math.abs(cprHands.y-patientTop)<0.06,'CPR hands must touch the patient chest surface');
updateAnnieArt(cpr,.1);
assert(cpr.userData.rig.compression>0,'M6 must animate repetitive mechanical CPR');

console.log('DUTYNIGHT V2 ANNIE IDENTITY QA PASS');
